version: 2

sources:
  - name: jaffle_shop
    database: jaffle-shop-507610  # Your GCP Project ID
    schema: raw                   # Your BigQuery Dataset name
    tables:
      - name: customers
      - name: orders